### ISSUE TITLE
phantomas: (254) Page loading failed

### ISSUE THREAD

**Issue by RSeidelsohn** [stefanjudis/grunt-phantomas#161] opened 2016-11-14 11:54 UTC
Before each run explained here I deleted my ./phantomas folder -  the output folder for the Frontend Statistics of grunt-phantomas.
My versions used are:
`phantomas v1.17.0` and `grunt-phantomas v0.13.0`.

When I run my grunt phantomas task with this configuration:
```
phantomas: {
    productionSite: {
        options: {
            buildUi   : true,
            assertions: {
                'jsErrors': 0,
            },
            indexPath : './phantomas/',
            url       : 'https://www.lesara.de/',
            options: {
            },
        },
    },
},
```
I get this result:
```
Running "phantomas:productionSite" (phantomas) task

PHANTOMAS EXECUTION(S) STARTED.
>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution not successful -> 252
>> Phantomas execution not successful -> 252
>> Phantomas execution not successful -> 252
>> Phantomas execution not successful -> 252
>> Phantomas execution not successful -> 252

WRITING RESULT FILES.
>> SOMETHING WENT WRONG...
>> No run was successful.
```
The files created by grunt-phantomas are then:
```
phantomas
├── data
└── images
    └── 1481791618461
        ├── screenshot-2016-12-15T08-46-58-1060.png
        ├── screenshot-2016-12-15T08-46-58-10803.png
        ├── screenshot-2016-12-15T08-46-58-1135.png
        ├── screenshot-2016-12-15T08-46-58-1212.png
        ├── screenshot-2016-12-15T08-46-58-1287.png
        ├── screenshot-2016-12-15T08-46-58-1372.png
        ├── screenshot-2016-12-15T08-46-58-16.png
        ├── screenshot-2016-12-15T08-46-58-4053.png
        ├── screenshot-2016-12-15T08-46-58-4160.png
        ├── screenshot-2016-12-15T08-46-58-508.png
        ├── screenshot-2016-12-15T08-46-58-687.png
        ├── screenshot-2016-12-15T08-46-58-762.png
        ├── screenshot-2016-12-15T08-46-58-851.png
        └── screenshot-2016-12-15T08-46-58-966.png
```

When I change the lines 719-722 in `./node_modules/grunt-phantomas/tasks/lib/phantomas.js` from
```
files = files.filter( function( file ) {
  return file.match( /\.json/gi );
} ).sort();
```
to
```
files = files[0].filter( function( file ) {
  return file.match( /\.json/gi );
} ).sort();
```
and use the same configuration, I get this result:
```
Running "phantomas:productionSite" (phantomas) task

PHANTOMAS EXECUTION(S) STARTED.
>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution not successful -> 252
>> Phantomas execution successful.
>> Phantomas execution not successful -> 252
>> Phantomas execution not successful -> 252
>> Phantomas execution not successful -> 252

WRITING RESULT FILES.
>> JSON file - phantomas/data/1481792147860.json - written.
>> CSV file - phantomas/data/1481792147860.csv - written.

CHECKING ALL WRITTEN FILES FOR VALID JSON.
>> '1481792147860.json' looks good!

BUILDING THE UI TO DISPLAY YOUR DATA.

PHANTOMAS index.html WRITING STARTED.
>> Phantomas created new 'index.html' at './phantomas/'.

CHECKING FOR NOT DISPLAYED METRICS.
>> You are currently not displaying the following metrics:
>> videoCount, videoSize, oldCachingHeaders, documentHeight, imagesScaledDown, DOMidDuplicated, hiddenImages, DOMmutationsInserts, DOMmutationsRemoves, DOMmutationsAttributes, DOMqueriesWithoutResults, DOMqueriesAvoidable, eventsDispatched, eventsScrollBound, globalVariablesFalsy, headersBiggerThanContent, jQueryVersionsLoaded, jQueryWindowOnLoadFunctions, jQueryEventTriggers, jQueryDOMReads, jQueryDOMWrites, jQueryDOMWriteReadSwitches, closedConnections, lazyLoadableImagesBelowTheFold, repaints, firstPaint, requestsToFirstPaint, domainsToFirstPaint, requestsToDomContentLoaded, domainsToDomContentLoaded, requestsToDomComplete, domainsToDomComplete, assetsWithCookies, smallCssFiles, smallJsFiles, domInteractive, domContentLoaded, domContentLoadedEnd, domComplete, requestsWithTimeout

PHANTOMAS ASSETS COPYING STARTED.
>> Phantomas copied asset to './phantomas/public/styles/phantomas.css'.
>> Phantomas copied asset to './phantomas/public/scripts/d3.min.js'.
>> Phantomas copied asset to './phantomas/public/scripts/phantomas.min.js'.

FINISHED PHANTOMAS.

Done.
```
and this is the file structure then created by `grunt-phantomas`:
```
phantomas
├── data
│   ├── 1481792147860.csv
│   └── 1481792147860.json
├── images
│   └── 1481792147860
│       ├── screenshot-2016-12-15T08-55-47-1621.png
│       ├── screenshot-2016-12-15T08-55-47-16.png
│       ├── screenshot-2016-12-15T08-55-47-1824.png
│       ├── screenshot-2016-12-15T08-55-47-1900.png
│       ├── screenshot-2016-12-15T08-55-47-1979.png
│       ├── screenshot-2016-12-15T08-55-47-2053.png
│       ├── screenshot-2016-12-15T08-55-47-2159.png
│       ├── screenshot-2016-12-15T08-55-47-2233.png
│       ├── screenshot-2016-12-15T08-55-47-2263.png
│       ├── screenshot-2016-12-15T08-55-47-2310.png
│       ├── screenshot-2016-12-15T08-55-47-2384.png
│       ├── screenshot-2016-12-15T08-55-47-2472.png
│       ├── screenshot-2016-12-15T08-55-47-2504.png
│       ├── screenshot-2016-12-15T08-55-47-2595.png
│       ├── screenshot-2016-12-15T08-55-47-3884.png
│       └── screenshot-2016-12-15T08-55-47-9987.png
├── index.html
└── public
    ├── scripts
    │   ├── d3.min.js
    │   └── phantomas.min.js
    └── styles
        └── phantomas.css

6 directories, 22 files
```

But when I now add one simple option to the grunt configuration of `grunt-phantomas` - and it doesn't have to be this one, it seems as if it can be any option - :
```
phantomas: {
    productionSite: {
        options: {
            buildUi   : true,
            assertions: {
                'jsErrors': 0,
            },
            indexPath : './phantomas/',
            url       : 'https://www.lesara.de/',
            options: {
                'allow-domain'     : '.cloudfront.net',
            },
        },
    },
},
```
I get this output from running the grunt task:
```
Running "phantomas:productionSite" (phantomas) task

PHANTOMAS EXECUTION(S) STARTED.
>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254

WRITING RESULT FILES.
>> SOMETHING WENT WRONG...
>> No run was successful.
```
, no matter if I use the "fixed" or original version of `./node_modules/grunt-phantomas/tasks/lib/phantomas.js`.

The file structure created by the task is then:
```
phantomas
├── data
└── images
    └── 1481792779017
        └── screenshot-2016-12-15T09-06-19-16.png
```
 - only the first screenshot has been taken.

So the `allow-domain` option seems to break the whole task after the first screenshot and the array issue in `./node_modules/grunt-phantomas/tasks/lib/phantomas.js` seems to break the task after all screenshots have been taken.

**Comment by stefanjudis** [comment] 2016-11-14 12:36
Hey @RSeidelsohn,

this doesn't seem to be an issue on `grunt-phantomas` side. 

I just tried your configuration on the cli using phantomas itself and this succeeds.

`phantomas https://www.lesara.de --verbose --no-externals --allow-domain=daol3a7s7tps6.cloudfront.net --timeout=2000 --analyze-css --ignore-ssl-errors --ssl-protocol=any`

Complete output can be found here 👉 https://gist.github.com/stefanjudis/77c61890788d71279a987459c9abece7

Nevertheless doing the same configuration using the commonJS module failes constantly with .

```
// test.js
const phantomas = require('phantomas');

phantomas(
  'https://www.lesara.de/',
  {
    'no-externals'     : true,
    'allow-domain'     : 'daol3a7s7tps6.cloudfront.net',
    'timeout'          : 2000,
    'analyze-css'      : true,
    'film-strip'       : false,
    'ignore-ssl-errors': true,
    'ssl-protocol'     : 'any',
    'web-security'     : false,
  }
).then( console.log, ( code ) => {
  console.log( `FAILED WITH ${code}` );
});
```

```
// output
~/Projects/grunt-phantomas | 😺 🐴 🐋 master (╯°□°)╯

> node test.js
FAILED WITH 254
```

So I don't think I can do much about it here as I think the issue is based in phantomas itself. 
So can you maybe open an issue over there? 

cc. @macbre

**Comment by RSeidelsohn** [comment] 2016-12-15 07:54
Ok, @stefanjudis, please be indulgent with me. New insights to this issue:

When I run my **grunt-phantomas** task, I get 
```>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254

WRITING RESULT FILES.
>> SOMETHING WENT WRONG...
>> No run was successful.
```

Configuration:
```// phantomas - Collect live statistics using PhantomJS (https://npmjs.org/package/grunt-phantomas)
phantomas: {
    productionSite: {
        options: {
            buildUi   : true,
            assertions: {
                'jsErrors': 0,
            },
            indexPath : './<%= directories.phantomas_dist %>/',
            url       : 'https://www.lesara.de/',
            options: {
                'no-externals'     : true,
                'allow-domain'     : '.cloudfront.net',
                'timeout'          : 60,
                'analyze-css'      : true,
                'film-strip'       : false,
                'ignore-ssl-errors': true,
                'ssl-protocol'     : 'any',
                'verbose'          : true,
                'debug'            : true,
                'engine'           : 'webkit',
                'log': './phantomas.log',
                'web-security'     : false,
            },
        },
    },
},
```
While when I comment out the options.options.allow-domain line, I get this output:

```
Running "phantomas:productionSite" (phantomas) task

PHANTOMAS EXECUTION(S) STARTED.
creating index directory...
>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution successful.
>> Phantomas execution successful.
>> Phantomas execution successful.
>> Phantomas execution successful.
>> Phantomas execution successful.

WRITING RESULT FILES.
>> JSON file - phantomas/data/1481786470392.json - written.
>> CSV file - phantomas/data/1481786470392.csv - written.

CHECKING ALL WRITTEN FILES FOR VALID JSON.
Unhandled rejection TypeError: file.match is not a function
    at /home/roman/Development/lesara/node_modules/grunt-phantomas/tasks/lib/phantomas.js:727:23
    at Array.filter (native)
    at null.<anonymous> (/home/roman/Development/lesara/node_modules/grunt-phantomas/tasks/lib/phantomas.js:723:23)
    at null.tryCatcher (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:617:18)
    at /home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/nodeback.js:45:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I still don't understand why the 'allow-domain' option breaks the run. But anyway I wanted to track down the above issue and it turns out that in the file `./node_modules/grunt-phantomas/tasks/lib/phantomas.js` from line 719 on the code 
```
files = files.filter( function( file ) { 
  return file.match( /\.json/gi );
} ).sort();
``` 
breaks because files looks like this:
```
files:
[ [ '1481726266330.csv',
    '1481726266330.json',
 ...
   '1481786871323.csv',
    '1481786871323.json' ] ]
```
i.e. it contains another array, so that the `match` operator can not be applied because file - which is expected to be a single string instead of an array of string - still looks like that:
```
file:
[ '1481726266330.csv',
  '1481726266330.json',
...
  '1481786871323.csv',
  '1481786871323.json' ]
```
So I simply added the line `files = files[0];` before that code:
```
files = files[0];
files = files.filter( function( file ) {
  return file.match( /\.json/gi );
} ).sort();
```
 and then everything seems to run smotthly, except that no images for the film strip are being created - due to the commented out `allow-domain` entry in combination with `no-externals`. Only if I comment out the whole `options.options` configuration in my Gruntfile.js do I get screenshots, but then I get the `>> Phantomas execution not successful -> 252` error - with code 252 instead of 254.

This whole JS code is way too complicated for me to understand why the files array is nested within another array, thus breaking the creation of the final output and why the `allow-domain` rule (which I set to `.cloudfromt.net`) prevents the whole run.

I would understand if this is too wild for you to take any care of, but if not I would be so happy if this issue could be tracked down and fixed. Something seems to be broken in my installation.

Cheers, Roman.

**Comment by RSeidelsohn** [comment] 2016-12-15 08:07
The Frontend Statistics btw. are somehow broken, too - possibly because of these two logged JS errors:

```
jsErrors in last execution
TypeError: null is not an object (evaluating 'body.scrollHeight') - unknown fn: undefined @ 7 / unknown fn: @ 8
TypeError: null is not an object (evaluating 'document.body.getElementsByTagName') - unknown fn: undefined @ 5 / unknown fn: @ 59 / unknown fn: @ 60
```

**Comment by RSeidelsohn** [comment] 2016-12-15 08:21
Many values in the Frontend Statistics are 0:

![frontend statistics forhttps www lesara de - 3](https://cloud.githubusercontent.com/assets/870515/21216558/bda6eec8-c2a7-11e6-90d4-4ec0974f46a6.png)

and the JS errors tracked are:
```
jsErrors in last execution
TypeError: null is not an object (evaluating 'body.scrollHeight') - unknown fn: undefined @ 7 / unknown fn: @ 8
TypeError: null is not an object (evaluating 'document.body.getElementsByTagName') - unknown fn: undefined @ 5 / unknown fn: @ 59 / unknown fn: @ 60
```

**Comment by stefanjudis** [comment] 2017-01-08 16:34
@RSeidelsohn 

I just released https://github.com/stefanjudis/grunt-phantomas/releases/tag/v0.14.0.

It includes a heavy dependency update and better timeout and error handling.

Could you please check if this issue here remains?

**Comment by stefanjudis** [comment] 2017-01-18 12:55
@RSeidelsohn ping. :)

**Comment by RSeidelsohn** [comment] 2017-01-18 13:48
Hi @stefanjudis , thx a lot for that! I'll try ASAP and tell you about the outcome - we're just currently heavily busy with a new project that uses gulp (which makes me think of maybe porting grunt-phantomas to gulp one day - as my do-your-own-project days task).

**Comment by stefanjudis** [comment] 2017-01-18 13:50
Ja I started this effort already years ago...

👉 https://www.npmjs.com/package/phantomas-ui -  would mean to remove all grunt code and make it a proper standalone module...

I'm happy to give you access if you wanna tackle it. :)

**Comment by stefanjudis** [comment] 2017-02-10 14:32
@RSeidelsohn ping. :)

Will close this one soon then.

**Comment by stefanjudis** [comment] 2017-02-12 15:05
We can reopen it it then if needed.

**Closed by stefanjudis** 2017-02-12 15:05 UTC
